FROM node:25-alpine

WORKDIR /app

# Install pnpm with fixed version
RUN corepack enable && corepack prepare pnpm@9.15.0 --activate

COPY package.json pnpm-lock.yaml .npmrc* ./

RUN pnpm install --frozen-lockfile

COPY . .

ENV ENV_NAME=test
ENV NODE_ENV=test

EXPOSE 8001

CMD ["pnpm", "test"]
