import { AUTH_CONFIG } from "./auth.config.js";
import { ENV_CONFIG } from "./env.config.js";

export const OPENAPI_CONFIG = {
  exposeRoute: true,
  openapi: {
    components: {
      securitySchemes: {
        apiKey: {
          in: "header",
          name: "apiKey",
          type: "apiKey",
        },
        bearerAuthRefresh: {
          bearerFormat: "JWT",
          description: "Refresh Token for obtaining new Access Token",
          in: "header",
          name: AUTH_CONFIG.refreshTokenKey,
          type: "apiKey",
        },
        bearerTokenAuth: {
          bearerFormat: "JWT", // optional, arbitrary value for documentation purposes
          in: "header",
          name: "Bearer Token",
          scheme: "bearer",
          type: "http",
        },
      },
    },
    consumes: ["application/json"],
    externalDocs: {
      description: "Find more info here",
      url: "https://swagger.io",
    },
    host: "localhost:3000",
    info: {
      description: "Autogenerated API documentation",
      title: "API documentation",
      version: ENV_CONFIG.VERSION || "1.0.0",
    },
    produces: ["application/json"],
    schemes: ["http", "https"],
    tags: [{ description: "Dev related end-points", name: "dev" }],
  },
  routePrefix: "/docs",
};
